### ISSUE TITLE
Program won't start

### ISSUE THREAD

**Issue by MauriceMohlek** [Sirrix-AG/PanBox#4]
I wasn't able to get the client start.

It seems something is missing on my Linux?!

<code>
localhost% ./start.sh 
2015-03-20 18:29:56,955 [main] (org.panbox) - Panbox directory for configuration () does not exists, reset to default: /home/xxxx/.panbox
2015-03-20 18:29:57,651 [main] (org.panbox) - Maximum supported key size: 2147483647
2015-03-20 18:29:57,731 [main] (org.panbox) - Could not find a specified library.
java.lang.UnsatisfiedLinkError: no unix-java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at cx.ath.matthew.unix.UnixSocket.<clinit>(UnixSocket.java:33)
	at org.freedesktop.dbus.Transport.connect(Transport.java:772)
	at org.freedesktop.dbus.Transport.<init>(Transport.java:737)
	at org.freedesktop.dbus.DBusConnection.<init>(DBusConnection.java:299)
	at org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:282)
	at org.panbox.desktop.linux.dbus.DBusService.isRunning(Unknown Source)
	at org.panbox.desktop.linux.CrashHandler.checkPanboxProcessRunning(Unknown Source)
	at org.panbox.desktop.linux.PanboxClient.checkPanboxProcessesRunning(Unknown Source)
	at org.panbox.desktop.common.PanboxClient.<init>(Unknown Source)
	at org.panbox.desktop.linux.PanboxClient.<init>(Unknown Source)
	at org.panbox.desktop.linux.PanboxClient.main(Unknown Source)
</code>

**Comment by caschulz88** [comment]
Hey,

thanks for contacting us. Indeed you are missing some packages. Please take a look into the readme.txt files that is also part of the extracted zip archive or tell me your distribution and I will post a list of needed packages.

**Comment by MauriceMohlek** [comment]
Ah yeah .. Shame on me.
I read the README.md

Didn't noticed the readme.txt inside the zip.
Now everything runs smooth :)
Thanks

**Comment by caschulz88** [comment]
Feel free to open another issue in case you might run into any problem. Thanks!
